### ISSUE TITLE
self hosted video support

### ISSUE THREAD

**Issue by 5shekel** [HydraWiki/mediawiki-embedvideo#26]
hi, it unclear to me if this is supported or not, but i host my own MP4 files
is there a way to play them using embedvideo extension?

**Comment by Alexia** [comment]
Not at the moment.  EmbedVideo is mainly designed for handling external services that may or may not require their own custom video players.

**Comment by distancesprinter** [comment]
I'd like to add my vote for self-hosted HTML5 video embedding (mp4 or ogg files).  It seems like there is not a good extension to do this, and it's important for organizations using MediaWiki internally as a knowledge transfer tool.  Adding self hosted video would further validate the EmbedVideo extension as the predominant video extension for MediaWiki.  Thanks for taking over the extension!

**Comment by Alexia** [comment]
@distancesprinter
What about TimedMediaHandler?  It does a good job with self hosted video and audio.  It is actively maintained.

https://www.mediawiki.org/wiki/Extension:TimedMediaHandler

**Comment by distancesprinter** [comment]
Doesn't look like that extension is stable, nor does it support mp4
containers from what I can tell.

**Comment by Alexia** [comment]
It does support MP4 if explicitly turned on:
````
$wgTmhEnableMp4Uploads = true;
````
It is stable enough.  It is used on Wikimedia sites, Wikia, and Gamepedia.

**Comment by distancesprinter** [comment]
Alright I'll give it a shot.  Thanks!

**Comment by Alexia** [comment]
Support for locally hosted video and audio is currently in the 2.4.0-alpha in the feature/media-handlers branch.
