### ISSUE TITLE
blank page with embedvideo

### ISSUE THREAD

**Issue by grantiago** [HydraWiki/mediawiki-embedvideo#48]
MediaWiki 	1.26.2
PHP 	5.3.28 (cgi-fcgi)
MySQL 	5.5.48-cll
ICU 	4.2.1
embed today snapshot 2/26/14
enabled embedvideo results in blank page
Parse error: syntax error, unexpected '[' in /wiki/extensions/EmbedVideo/EmbedVideo.i18n.magic.php on line 12

**Comment by Alexia** [comment]
PHP 5.3 is not supported by EmbedVideo.  There is an older compatibility branch that may not support all video services that does support PHP 5.3.
https://github.com/HydraWiki/mediawiki-embedvideo/tree/compat

Please note that both PHP 5.3 and 5.4 are no longer receiving security updates from The PHP Group.
http://php.net/eol.php

**Comment by grantiago** [comment]
Thanks. Lazy me. I upgraded my php to 5.6.18. The error is gone. However, EmbedVideo works only in Chrome, windows 7. On Firefox windows -- Just a thumbnail and spinning loader. I don't have IE installed. Blank space on all android browsers: stock, chrome, firefox. I checked some samples on help.gamepedia.com -- same results across the board. I'm using mobile frontend 1.0.0 and was having the same problem with Semantic Maps. At least on the mobile end. 
this was the semantic maps fix:  https://www.mediawiki.org/wiki/ResourceLoader/Writing_a_MobileFrontend_friendly_ResourceLoader_module#Enabling_your_existing_modules. cheers.

**Comment by grantiago** [comment]
whoops. restarted firefox on the desktop and it is working now. android the same.

**Comment by Alexia** [comment]
Yeah, ever since about Firefox 40 I have been having a similar problem.  Restarting Firefox always seems to fix it.

The mobile targeting should still be done and I made a ticket for it.

https://github.com/HydraWiki/mediawiki-embedvideo/issues/49
