### ISSUE TITLE
EmbedVideo doesn't work with mw-collapsible class

### ISSUE THREAD

**Issue by KyoriAsh** [HydraWiki/mediawiki-embedvideo#54]
http://en.touhouwiki.net/wiki/MikuMikuDance

As of the link above, NicoVideo seems doesn't hide properly when using mw-collapsible, and displayed all embedvideo at the bottom of the page. May you solve the problem for NicoVideo? Thanks in advance.

**Comment by applehat** [comment]
It appears this issue is not with mw-collapsible, but with NicoVideo all together.

Looking into a fix.

**Comment by applehat** [comment]
This issue is resolved in the 2.3.1 branch. You can either copy the fix from the commit above, or wait for the 2.3.1 release =)

**Comment by KyoriAsh** [comment]
Thanks for the info, I will check it as soon as possible
