### ISSUE TITLE
Embed video error

### ISSUE THREAD

**Issue by danieljrossouw** [HydraWiki/mediawiki-embedvideo#57]
I have installed the extension as per instruction to the point that special/version indicates successful installation: 
![image](https://cloud.githubusercontent.com/assets/20353521/16682518/4b98f3aa-44fb-11e6-841c-ee2229738df7.png)

Yet, when I use the parsing to embed a video and save, I get an HTTP 500 error:
![image](https://cloud.githubusercontent.com/assets/20353521/16682460/161146ec-44fb-11e6-8b14-5fb2c2d9818f.png)

Please assist

**Comment by Alexia** [comment]
Can you provide the actually back trace and/or error from the server logs?

**Comment by danieljrossouw** [comment]
I fixed it. Thanks.
