### ISSUE TITLE
Problem with mediawiki and load video

### ISSUE THREAD

**Issue by ricca82it** [HydraWiki/mediawiki-embedvideo#69]
Hi , i have a problem with version mediawiki-embedvideo-2.5.0 and 

Prodotto    Versione
MediaWiki   1.27.1
PHP 5.6.22 (cgi-fcgi)
MySQL   5.6.33-79.0-log
ICU 50.1.2

When i try to load a mp4 file i have some error/warning (the load work fine and i have able to reproduce the video correctly)

Strict Standards: Accessing static property EmbedVideo\FFProbe::$file as non static in /web/htdocs/www.sorpresiamo.it/home/extensions/EmbedVideo/classes/media/FFProbe.php on line 128

Warning: shell_exec() has been disabled for security reasons in /web/htdocs/www.sorpresiamo.it/home/extensions/EmbedVideo/classes/media/FFProbe.php on line 128

Strict Standards: Accessing static property EmbedVideo\FFProbe::$metadata as non static in /web/htdocs/www.sorpresiamo.it/home/extensions/EmbedVideo/classes/media/FFProbe.php on line 135

Strict Standards: Accessing static property EmbedVideo\FFProbe::$metadata as non static in /web/htdocs/www.sorpresiamo.it/home/extensions/EmbedVideo/classes/media/FFProbe.php on line 51

Warning: shell_exec() has been disabled for security reasons in /web/htdocs/www.sorpresiamo.it/home/extensions/EmbedVideo/classes/media/FFProbe.php on line 128

Warning: shell_exec() has been disabled for security reasons in /web/htdocs/www.sorpresiamo.it/home/extensions/EmbedVideo/classes/media/FFProbe.php on line 128

Warning: shell_exec() has been disabled for security reasons in /web/htdocs/www.sorpresiamo.it/home/extensions/EmbedVideo/classes/media/FFProbe.php on line 128

Warning: shell_exec() has been disabled for security reasons in /web/htdocs/www.sorpresiamo.it/home/extensions/EmbedVideo/classes/media/FFProbe.php on line 128

Warning: shell_exec() has been disabled for security reasons in /web/htdocs/www.sorpresiamo.it/home/extensions/EmbedVideo/classes/media/FFProbe.php on line 128

Warning: shell_exec() has been disabled for security reasons in /web/htdocs/www.sorpresiamo.it/home/extensions/EmbedVideo/classes/media/FFProbe.php on line 128

Warning: shell_exec() has been disabled for security reasons in /web/htdocs/www.sorpresiamo.it/home/extensions/EmbedVideo/classes/media/FFProbe.php on line 128

Warning: shell_exec() has been disabled for security reasons in /web/htdocs/www.sorpresiamo.it/home/extensions/EmbedVideo/classes/media/FFProbe.php on line 128

Warning: shell_exec() has been disabled for security reasons in /web/htdocs/www.sorpresiamo.it/home/extensions/EmbedVideo/classes/media/FFProbe.php on line 128

Warning: shell_exec() has been disabled for security reasons in /web/htdocs/www.sorpresiamo.it/home/extensions/EmbedVideo/classes/media/FFProbe.php on line 128

**Comment by Alexia** [comment]
To get metadata from locally hosted files ffmpeg has to be installed on the server and the PHP process has to be able to call ffmpeg through shell_exec().  If you are on shared hosting this will most likely not work for you.

**Comment by ricca82it** [comment]
I Can disable the retrieves of metadata for locally file?

**Comment by ricca82it** [comment]
I Can disable the retrieves of metadata for locally file?

Il 24 Ott 2016 22:48, "Alexia E. Smith" <notifications@github.com> ha
scritto:

**Comment by Alexia** [comment]
This is improved with the v2.5.2 release.  If there are any additional issues that come up with your particular server environment please open a new issue report for them.
