### ISSUE TITLE
Problem with loading video file

### ISSUE THREAD

**Issue by yongxinL** [HydraWiki/mediawiki-embedvideo#75]
Hi, I have a problem with the version mediawiki-embedvideo 2.6.0 and detailed environment:

MediaWiki 1.28.0
PHP 7.0.15 (php-fpm)
MariaDB 10.1.20

When I tried to load a mp4 file via maintenance/importImages.php and receive below warning / error message (the file has be imported and I am able to see load the file into a page), it also get same error when I tried to rebuild by maintenance/rebuildall.php

Thanks.

[error] [86dc728b1305c939700cd983] [no req]   ErrorException from line 174 of /var/wiki/extensions/EmbedVideo/classes/media/FFProbe.php: PHP Notice: Accessing static property EmbedVideo\StreamInfo::$info as non static
#0 /var/wiki/extensions/EmbedVideo/classes/media/FFProbe.php(174): MWExceptionHandler::handleError(integer, string, string, integer, array)
#1 /var/wiki/extensions/EmbedVideo/classes/media/FFProbe.php(214): EmbedVideo\StreamInfo->getField(string)
#2 /var/wiki/extensions/EmbedVideo/classes/media/VideoHandler.php(101): EmbedVideo\StreamInfo->getWidth()
#3 /var/wiki/extensions/EmbedVideo/classes/media/VideoHandler.php(45): EmbedVideo\VideoHandler->getImageSize(LocalFile, string)
#4 /var/wiki/extensions/EmbedVideo/classes/media/VideoHandler.php(119): EmbedVideo\VideoHandler->normaliseParams(LocalFile, array)
#5 /var/wiki/includes/media/MediaHandler.php(266): EmbedVideo\VideoHandler->doTransform(LocalFile, string, string, array, integer)
#6 /var/wiki/includes/filerepo/file/File.php(1082): MediaHandler->getTransform(LocalFile, string, string, array)
#7 /var/wiki/includes/Linker.php(759): File->transform(array)
#8 /var/wiki/includes/Linker.php(532): Linker::processResponsiveImages(LocalFile, EmbedVideo\VideoTransformOutput, array)
#9 /var/wiki/includes/parser/Parser.php(5325): Linker::makeImageLink(Parser, Title, LocalFile, array, array, boolean, boolean, integer)
#10 /var/wiki/includes/parser/Parser.php(2323): Parser->makeImage(Title, array, LinkHolderArray)
#11 /var/wiki/includes/parser/Parser.php(2075): Parser->replaceInternalLinks2(string)
#12 /var/wiki/includes/parser/Parser.php(1290): Parser->replaceInternalLinks(string)
#13 /var/wiki/includes/parser/Parser.php(441): Parser->internalParse(string)
#14 /var/wiki/includes/content/WikitextContent.php(330): Parser->parse(string, Title, ParserOptions, boolean, boolean, NULL)
#15 /var/wiki/includes/content/AbstractContent.php(497): WikitextContent->fillParserOutput(Title, NULL, ParserOptions, boolean, ParserOutput)
#16 /var/wiki/includes/content/AbstractContent.php(230): AbstractContent->getParserOutput(Title, NULL, ParserOptions, boolean)
#17 /var/wiki/maintenance/refreshLinks.php(264): AbstractContent->getSecondaryDataUpdates(Title)
#18 /var/wiki/maintenance/refreshLinks.php(186): RefreshLinks::fixLinksFromArticle(integer, boolean)
#19 /var/wiki/maintenance/refreshLinks.php(68): RefreshLinks->doRefreshLinks(integer, boolean, string, boolean, boolean)
#20 /var/wiki/maintenance/rebuildall.php(60): RefreshLinks->execute()
#21 /var/wiki/maintenance/doMaintenance.php(111): RebuildAll->execute()
#22 /var/wiki/maintenance/rebuildall.php(67): require_once(string)
#23 {main}

**Comment by Alexia** [comment]
Fixed.

https://github.com/HydraWiki/mediawiki-embedvideo/commit/056b7e54722e03f5fd20e2bb08289fa4955d3148
