### ISSUE TITLE
cannot override extensions list to prevent uploads

### ISSUE THREAD

**Issue by obfuscateddevices** [HydraWiki/mediawiki-embedvideo#76]
Hello,

    I'm mostly using this plugin to display youtube videos but it is adding file extensions to the allowed formats for uploading and I can't seem to override them with $wgFileExtensions. I would like to beable to disable uploads for videos and/or specify which formats would be allowable.

Thanks

Adrian

**Comment by Alexia** [comment]
I added configuration options for this and it will be in the next release.

https://github.com/HydraWiki/mediawiki-embedvideo/commit/b650d8bbfab4803ee483540bf48ced2c7c316d03
