### ISSUE TITLE
Warning: array_merge(): Argument #2 is not an array in EmbedVideo.hooks.php on line 281

### ISSUE THREAD

**Issue by rshwayder** [HydraWiki/mediawiki-embedvideo#77]
Getting an error sometimes--not always--at the top of the page as follows.

Warning: array_merge(): Argument #2 is not an array in EmbedVideo.hooks.php on line 281

**Comment by Alexia** [comment]
Fixed: https://github.com/HydraWiki/mediawiki-embedvideo/commit/23dfdc80d7956f5de127a0116646ab197c440eeb

This will be packaged into a future release.
