### ISSUE TITLE
Many errors

### ISSUE THREAD

**Issue by scottsealanddesign** [HydraWiki/mediawiki-embedvideo#83]
I was getting a bunch of errors with this plugin all related to VideoTransformOutput.php

It looks like if $parameters['start'] or $parameters['end'] is blank then the code throws many errors. 

So I added a conditional check to these in the file and it works now: 
![added-videotransformoutput](https://user-images.githubusercontent.com/18123576/27244858-7e3edcec-52b6-11e7-911d-8c09e8312c35.jpg)

**Comment by Alexia** [comment]
Fixed with change bde1278e2fcad697570645400e6f7eeb9867cb29.
