### ISSUE TITLE
Embedvideo Extension breaks my Mediawiki...

### ISSUE THREAD

**Issue by michell-la** [HydraWiki/mediawiki-embedvideo#95]
MediaWiki | 1.30.0
PHP | 7.0.26 (fpm-fcgi)
MySQL | 5.7.20
ICU | 52.1

I've been rebuilding a mediawiki build from a backed up database - and in the process of adding embedvideo so my existing links work.

I've unzipped the 2.7 release to my extensions directory...

And then enabled the extension with an edit to the LocalSettings.php file with:

wfLoadExtension( 'EmbedVideo' );

Once I save the file in vi. The mediawiki page (all of them refuse to load)... I just get a blank pages with no data at all. 

Remarking the extension out - restores the site to normal functionality...

Examining the wiki mark up, I see i haven't been consistent in the way I've used the tags... Some appear as raw:

{{#ev:youtube|80IgFaBaNco}}

whereas some of my pages have the more extended mark-up

{{#ev:youtube|3QX3cH7_56k||center|Show Me How with @ twitterhandle - Set to 720p, Full Screen}}

I wondered if the difference in the way the pages are marked up is causing the problem and if i'm using characters that extension no longer handles... The site was built on a previous release of mediawiki and the extension where this wasn't a problem...

Thanks in advance
Michelle

**Comment by michell-la** [comment]
No responses? I guess this works perfectly for everyone out of the box - and I'm the only one experiencing issues? :)

**Comment by Alexia** [comment]
I have not tested with MediaWiki 1.30.x yet so that might have something to do with it.

**Comment by michell-la** [comment]
K. I've also pointed out to my hosting provider that the versions of PHP are very old - but I'm on a shared infrastructure - so they are unwilling to upgrade for fear of impact on others I think. Shades of 1990's hosting I think.

Thank you for your response... :)

**Comment by Alexia** [comment]
PHP 5.6 or 7.0 should be fine to support the code.

**Comment by michell-la** [comment]
My theory is something to do with the 'string's used to call the video. Perhaps some security setting has been introduced as i'm not sure how "standard" {{ }} is as an escape character is in wiki markup...

**Comment by michell-la** [comment]
I resolved my problem. By ditching this extension. I found https://www.mediawiki.org/wiki/Extension:YouTube worked with my version of mediawiki. It was pain finding and replacing the wiki text. but it got the job done in the end...
